# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Unbuffered output
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install dependencies
COPY pyproject.toml uv.lock* ./
RUN pip install --no-cache-dir .

# Copy application code
COPY src ./src

# Default command to run the MCP server over stdio
CMD ["python3", "-u", "src/qgis_mcp/qgis_mcp_server.py"]
